# Generated by Django 5.2.9 on 2026-01-27 20:02

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('api_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(default='Moje Terrarium', max_length=100)),
                ('temp_day', models.FloatField(default=28.0, verbose_name='Temp. Dzień')),
                ('temp_night', models.FloatField(default=22.0, verbose_name='Temp. Noc')),
                ('alerts_enabled', models.BooleanField(default=True, verbose_name='Alerty Email włączone')),
                ('alert_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do powiadomień')),
                ('alert_min_temp', models.FloatField(default=18.0, verbose_name='Alarm Min Temp')),
                ('alert_max_temp', models.FloatField(default=35.0, verbose_name='Alarm Max Temp')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('light_start', models.TimeField(default=datetime.time(8, 0))),
                ('light_end', models.TimeField(default=datetime.time(20, 0))),
                ('light_mode', models.CharField(choices=[('auto', 'Automat'), ('manual', 'Ręczny')], default='auto', max_length=10)),
                ('light_manual_state', models.BooleanField(default=False, verbose_name='Stan ręczny')),
                ('mist_enabled', models.BooleanField(default=True)),
                ('mist_mode', models.CharField(choices=[('harmonogram', 'Harmonogram'), ('auto', 'Auto')], default='harmonogram', max_length=20)),
                ('mist_duration', models.IntegerField(default=10, help_text='Czas zraszania w sekundach')),
                ('mist_min_humidity', models.IntegerField(default=60, verbose_name='Min Wilgotność %')),
                ('mist_h1', models.TimeField(blank=True, null=True)),
                ('mist_h2', models.TimeField(blank=True, null=True)),
                ('mist_h3', models.TimeField(blank=True, null=True)),
                ('mist_h4', models.TimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrariums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('heater', models.BooleanField(default=False)),
                ('mist', models.BooleanField(default=False)),
                ('light', models.BooleanField(default=False)),
                ('terrarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.terrarium')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['terrarium', 'timestamp'], name='core_readin_terrari_e79fa2_idx')],
            },
        ),
    ]
