# Generated by Django 5.2.9 on 2026-01-14 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID Urządzenia')),
                ('pin_hash', models.CharField(max_length=255, verbose_name='Hash PINu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(default='Moje Terrarium', max_length=100)),
                ('temp_day', models.FloatField(default=28.0, verbose_name='Temp. Dzień')),
                ('temp_night', models.FloatField(default=22.0, verbose_name='Temp. Noc')),
                ('light_start', models.TimeField(default='08:00')),
                ('light_end', models.TimeField(default='20:00')),
                ('mist_enabled', models.BooleanField(default=True)),
                ('mist_mode', models.CharField(choices=[('harmonogram', 'Harmonogram'), ('auto', 'Auto')], default='harmonogram', max_length=20)),
                ('mist_duration', models.IntegerField(default=10, help_text='Czas zraszania w sekundach')),
                ('mist_min_humidity', models.IntegerField(default=60, verbose_name='Min Wilgotność %')),
                ('mist_h1', models.TimeField(blank=True, null=True)),
                ('mist_h2', models.TimeField(blank=True, null=True)),
                ('mist_h3', models.TimeField(blank=True, null=True)),
                ('mist_h4', models.TimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrariums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('is_heater_on', models.BooleanField(default=False)),
                ('is_mist_on', models.BooleanField(default=False)),
                ('is_light_on', models.BooleanField(default=False)),
                ('terrarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.terrarium')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['terrarium', 'timestamp'], name='core_readin_terrari_e79fa2_idx')],
            },
        ),
    ]
