# Generated by Django 6.0.3 on 2026-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='mist_d1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_d9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h10',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h11',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h12',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h6',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h7',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h8',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='mist_h9',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='mist_duration',
            field=models.IntegerField(default=10, help_text='Globalny czas zraszania w sekundach (dla trybu Auto)'),
        ),
    ]
