# Generated by Django 5.2.9 on 2026-01-14 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='light_end',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='light_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
