# Generated by Django 5.2.9 on 2026-01-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('avg_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_hum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('terrarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terrarium')),
            ],
            options={
                'indexes': [models.Index(fields=['terrarium', 'timestamp'], name='core_hourly_terrari_359501_idx')],
            },
        ),
    ]
