# Generated by Django 5.2.9 on 2026-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hourlyreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='is_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='is_lighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='is_misting',
            field=models.BooleanField(default=False),
        ),
    ]
