# Generated by Django 5.2.9 on 2026-01-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_terrarium_api_token_alter_terrarium_light_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='light_manual_state',
            field=models.BooleanField(default=False, verbose_name='Stan ręczny'),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='light_mode',
            field=models.CharField(choices=[('auto', 'Automat'), ('manual', 'Ręczny')], default='auto', max_length=10),
        ),
    ]
