# Generated by Django 5.2.9 on 2026-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_terrarium_light_manual_state_terrarium_light_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='alert_max_temp',
            field=models.FloatField(default=35.0, verbose_name='Alarm Max Temp'),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='alert_min_temp',
            field=models.FloatField(default=18.0, verbose_name='Alarm Min Temp'),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='alerts_enabled',
            field=models.BooleanField(default=True, verbose_name='Alerty Email włączone'),
        ),
        migrations.AddField(
            model_name='terrarium',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
