# Generated by Django 5.2.9 on 2026-01-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_terrarium_is_heating_terrarium_is_lighting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='update_required',
            field=models.BooleanField(default=False, verbose_name='Update OTA Required'),
        ),
    ]
