# Generated by Django 5.2.9 on 2026-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_terrarium_alert_max_temp_terrarium_alert_min_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do powiadomień'),
        ),
    ]
