# Generated by Django 5.2.9 on 2026-01-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_terrarium_alert_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alloweddevice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='alloweddevice',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alloweddevice',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='alloweddevice',
            name='pin_hash',
            field=models.CharField(max_length=128),
        ),
    ]
